services:
  postgres:
    image: postgres:16-alpine
    container_name: biblioteca_db
    environment:
      POSTGRES_USER: biblioteca_user
      POSTGRES_PASSWORD: biblioteca_password
      POSTGRES_DB: biblioteca_db
    ports:
      - "5434:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U biblioteca_user -d biblioteca_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: biblioteca_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@biblioteca.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False' # per evitare conflitti con altri db presenti in locale, questo Ã¨ l'unico con accesso senza password ed email prima di entrare
    ports:
      - "5051:80"  # messo porta 5051 per evitare conflitti con il servizio sulla 5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

  localstack:
    image: localstack/localstack:3.4
    container_name: biblioteca_localstack
    ports:
      - "4566:4566"  
    environment:
      SERVICES: sns,sqs
      PERSISTENCE: 1
      AWS_DEFAULT_REGION: us-east-1
      DEBUG: 0
    volumes:
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  init-localstack:
    image: python:3.12-slim
    container_name: biblioteca_init_localstack
    environment:
      AWS_ENDPOINT_URL: http://localstack:4566
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - ./scripts:/scripts
    depends_on:
      localstack:
        condition: service_healthy
    command: sh -c "pip install --no-cache-dir boto3 -q && python /scripts/init_localstack.py"
    restart: "no"

volumes:
  postgres_data:
  pgadmin_data:
  localstack_data: